# -*- coding: utf-8 -*-
"""Easy Text Summarization with Libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ohYwltnl-lZCd1IYdP4KKLpqS_NJ2Ol
"""

!pip install sumy

from sumy.summarizers.text_rank import TextRankSummarizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer

!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

import pandas as pd
import nltk

nltk.download('punkt_tab')

df = pd.read_csv('bbc_text_cls.csv')

df.head()

doc = df[df.labels == 'business']['text'].sample(random_state=42)

summarizer = TextRankSummarizer()
parser = PlaintextParser.from_string(doc.iloc[0].split('\n', 1)[1], Tokenizer('english'))
summary = summarizer(parser.document, sentences_count=5)

summary

for s in summary:
  print(s)

summarizer = LsaSummarizer()
summary = summarizer(parser.document, sentences_count=5)

for s in summary:
  print(s)

